# Generated by Django 5.0.1 on 2024-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('dept_short_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='contacts/media/uploads/')),
                ('phone', models.CharField(max_length=20)),
                ('contact_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
