# Generated by Django 5.0.1 on 2024-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officestaff',
            old_name='teacher_id',
            new_name='staff_id',
        ),
        migrations.AddField(
            model_name='officestaff',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
