# Generated by Django 5.0.1 on 2024-06-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice/media/uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice/media/uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('superadvisor', models.CharField(max_length=200)),
                ('Researchimage', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
                ('member1', models.CharField(blank=True, max_length=200, null=True)),
                ('member2', models.CharField(blank=True, max_length=200, null=True)),
                ('member3', models.CharField(blank=True, max_length=200, null=True)),
                ('member4', models.CharField(blank=True, max_length=200, null=True)),
                ('member5', models.CharField(blank=True, max_length=200, null=True)),
                ('member6', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=200)),
                ('paper_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
