# Generated by Django 5.0.1 on 2024-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice/media/uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice/media/uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/')),
            ],
        ),
    ]
