# Generated by Django 5.0.1 on 2024-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('superadvisor', models.CharField(max_length=200)),
                ('member1', models.CharField(blank=True, max_length=200, null=True)),
                ('member2', models.CharField(blank=True, max_length=200, null=True)),
                ('member3', models.CharField(blank=True, max_length=200, null=True)),
                ('member4', models.CharField(blank=True, max_length=200, null=True)),
                ('member5', models.CharField(blank=True, max_length=200, null=True)),
                ('member6', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=200)),
                ('paper_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
