# Generated by Django 5.0.1 on 2024-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='Researchimage',
            field=models.ImageField(blank=True, null=True, upload_to='notice/media/uploads/'),
        ),
    ]
